blank_issues_enabled: true

contact_links:
  - name: 问题反馈 / Bug Report
    url: https://github.com/simple-robot/simpler-robot/issues/new/choose
    about: 前往simbot问题统一反馈处 / Go to the summary of simbot issues

  - name: 讨论区 / Discussions
    url: https://github.com/orgs/simple-robot/discussions
    about: simbot交流讨论区
