name: Qodana
on:
  workflow_dispatch:
  pull_request:
    branches-ignore:
      - 'dependabot/**'
  push:
    branches:
      - dev/main
      - dev/master
      - main
      - master
      - '!dependabot/**'

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.3.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
