name: Test Branch
on:
  pull_request:
    branches:
      - 'dev/**'
    paths:
      - '**.java'
      - '**.kt'
      - '**.kts'
      - '*/src/*/kotlin/**'
      - '*/src/*/java/**'
      - '*/src/*/resource/**'
      - 'gradle/**'

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

env:
  IS_CI: true
  GRADLE_OPTS: "-Dfile.encoding=UTF-8"

jobs:
  build-test:
    name: Build and test
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
          cache: 'gradle'

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          add-job-summary-as-pr-comment: on-failure # Valid values are 'never' (default), 'always', and 'on-failure'

      - run: gradle build --scan

      - name: Run All Tests
        run: gradle assemble allTests -Porg.gradle.jvmargs='-Xmx4g -Xms2g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8' --info --warning-mode all --build-cache

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: test-reports-${{ runner.os }}
          path: '**/build/reports/tests'
          retention-days: 7

  detekt-check:
    name: Detekt check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
          cache: 'gradle'

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          add-job-summary-as-pr-comment: on-failure # Valid values are 'never' (default), 'always', and 'on-failure'


      - name: Run detekt
        run: gradle detekt

      - name: Upload detekt reports
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: detekt-reports
          path: 'build/reports/detekt'
          retention-days: 7

      # https://detekt.dev/docs/introduction/reporting/#integration-with-github-code-scanning
      # Make sure we always run this upload task,
      # because the previous step may fail if there are findings.
      - name: Upload SARIF to GitHub using the upload-sarif action
        uses: github/codeql-action/upload-sarif@v2
        if: ${{ always() }}
        with:
          sarif_file: 'build/reports/detekt/detekt.sarif'
